version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: proot
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: proot
      DB_DATABASE: server_db
      DB_HOST: mongodb
      DB_URL: mongodb://root:proot@0.0.0.0:27017/server_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge