version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_NAME: mydb
      DB_HOST: mongodb
      DB_URL: mongodb://root:example@0.0.0.0:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge