version: '3'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    command: nest start:prod --watch
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_NAME=watch-site
      - DB_URL=mongodb://root:example@db:27017/nest?authSource=admin&authMechanism=SCRAM-SHA-1
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=example
volumes:
  data: {}